### ISSUE TITLE
Vagrant doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by veeara282** [arky/iiab-dev-mode#9]
As part of my team project (main pull request [here](https://github.com/iiab/iiab/pull/894)), we tried to set up a staging server on an Ubuntu 18.04 virtual machine using Vagrant. While doing so, we ran into problems using `vagrant up`. We eventually switched to installing IIAB directly on the VM, but would like to provide the steps we took for the IIAB project's benefit.

---

The problem was that `vagrant up` was failing with the error `Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory`. We addressed this error by running the following commands:
```
vagrant plugin install vagrant-libvirt
sudo apt install qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils virt-manager
sudo adduser `whoami` libvirt
sudo adduser `whoami` libvirt-qemu
sudo /etc/init.d/libvirtd restart
```

and then logging out and back in to apply group membership to the current user. ([Source](https://bugs.launchpad.net/ubuntu/+source/vagrant-libvirt/+bug/1771430))

However, this did not solve the problem. We are still getting this error:
```
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: 
invalid argument: could not find capabilities for domaintype=kvm 
```

**Comment by arky** [comment]
Virtualbox is default provider in Vagrant. I felt that it much simpler for new developers to configure and use over other providers like libvirt.
 
https://github.com/arky/iiab-dev-mode/blob/master/Vagrantfile#L5

Thank you for using this code base and contributing patches. Much appreciated. But to be precise, this repo is designed to get new developers to setup a dev environment and contribute to IIAB on personal computers. It is not designed nor recommended to be deployed in a public facing server environment.
